apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admission-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/sumonaust/python-gitops.git
    targetRevision: main
    path: admission

  destination:
    server: https://kubernetes.default.svc
    namespace: python-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true  