apiVersion: apps/v1
kind: Deployment
metadata:
  name: admissionpf
  namespace: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apfapp
  template:
    metadata:
      labels:
        app: apfapp
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: apfcontainer
          image: daffodilsoftwaresection/test-admission-portal:a182ec4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 300m
